# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: false
font: native
font_size: M
# XS S M L XL

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: Sam Diabate, Physical Oceanographer.
twitter: ''

# Contact (edit or remove options as required)

email: samuel.diabate@mu.ie
# phone: 888 888 88 88
address:
  street: Eolas Building, North Campus, Maynooth University
  city: Maynooth
  region: Co. Kildare
  #  postcode: '94305'
  country: Ireland
  country_code: IE
coordinates:
  latitude: '53.38469039041169'
  longitude: '-6.6015132822729'
directions: Floor 3, corridor on the left when coming out of the stairs (on the right when taking the lift).
#office_hours: Rarely in office due to COVID19. Essentially, I am working from home. The easiest way to reach me is via mail.
# appointment_url: 'https://calendly.com'
# contact_links:
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: true
  show_day_night: true
  show_search: true
  highlight_active_link: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
math: true
diagram: false
privacy_pack: true
show_related:
  post: true
  project: true
  publication: true
  talk: true
reading_time: true
section_pager: false
sharing: true
copyright_license:
  enable: true
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This website is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
